### ISSUE TITLE
Error while running on Ubuntu 18.04

### ISSUE THREAD

**Issue by SlinkoIgor** [dmitry-kostin/termin-buchen#2]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle termin-buchen@1.0.0~precompile: termin-buchen@1.0.0
6 silly lifecycle termin-buchen@1.0.0~precompile: no script for precompile, continuing
7 info lifecycle termin-buchen@1.0.0~compile: termin-buchen@1.0.0
8 verbose lifecycle termin-buchen@1.0.0~compile: unsafe-perm in lifecycle true
9 verbose lifecycle termin-buchen@1.0.0~compile: PATH: /usr/share/npm/bin/node-gyp-bin:/home/aic/projects/termin-buchen/node_modules/.bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle termin-buchen@1.0.0~compile: CWD: /home/aic/projects/termin-buchen
11 silly lifecycle termin-buchen@1.0.0~compile: Args: [ '-c', 'tsc' ]
12 info lifecycle termin-buchen@1.0.0~compile: Failed to exec compile script
13 verbose stack Error: termin-buchen@1.0.0 compile: `tsc`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid termin-buchen@1.0.0
15 verbose cwd /home/aic/projects/termin-buchen
16 error Linux 5.4.0-135-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error termin-buchen@1.0.0 compile: `tsc`
24 error spawn ENOENT
25 error Failed at the termin-buchen@1.0.0 compile script 'tsc'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the termin-buchen package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     tsc
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs termin-buchen
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls termin-buchen
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
(END)

```

**Comment by dmitry-kostin** [comment]
try to [update node](https://nodejs.org/en/) version first, I guess v8.10.0 is kind of outdated
