### ISSUE TITLE
Get error -86 when running command npm start

### ISSUE THREAD

**Issue by vanshika-bawa** [dmitry-kostin/termin-buchen#23]
Hi, I am not very familiar with Node. I followed the readme and adapted the .env based on .env.example.

I run `npm start` and get:

> termin-buchen@1.0.0 start
> npm run prepare && node -r dotenv/config build/src/index.js

> termin-buchen@1.0.0 prepare
> npm run compile

> termin-buchen@1.0.0 compile
> tsc

(node:9153) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at Object.execFile (node:child_process:351:17)
    at module.exports.fileCommandJson (/Users/vaba01/PycharmProjects/termin-buchen/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/vaba01/PycharmProjects/termin-buchen/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at NotificationCenter.sendNotification (/Users/vaba01/PycharmProjects/termin-buchen/build/src/notifications/notification-center/index.js:8:36)
    at sendNotification (/Users/vaba01/PycharmProjects/termin-buchen/build/src/notifications/send-notification.js:11:46)
    at startAutomation (/Users/vaba01/PycharmProjects/termin-buchen/build/src/index.js:40:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

System: MacOS 14.3

termin-buchen % node -v
v21.6.2
termin-buchen % npm -v
10.2.4

**Comment by vanshika-bawa** [comment]
I also noticed that after trying to use the bot once, I no longer see the "There are no appointments.." message on the website from my laptop.

**Comment by dmitry-kostin** [comment]
The deprecation warning is likely due to using an incorrect version of nodejs. Could you try with the latest LTS version, 20.11.1? You can find it [here](https://nodejs.org/en/download), or you can alternatively use [NVM](https://github.com/nvm-sh/nvm). Also let me know if you are able to run script (usually depreciations are just warnings and not blockers).

> I no longer see the "There are no appointments.." message 

Regarding the message you mentioned, I can't see it either. This is something coming from the website, and we don't have control over it. I would suggest just keeping the bot on during business hours.

Let me know you progress.

**Comment by vanshika-bawa** [comment]
Hi, under the deprecation warning there is an error. 

I did `npm cache clean --force` and that fixed my issue.

thanks for quick assistance and for this software ;) will put it to work at business hours

**Comment by vanshika-bawa** [comment]
For the record: I got my first appointment in 1 day. But the date did not fit me so I am still trying my luck.
