### ISSUE TITLE
Fix for Error -86 on Mac Silicon due to node-notifier

### ISSUE THREAD

**Issue by alikhtag** [dmitry-kostin/termin-buchen#24]
Not really an issue just a helpful info. I can make a PR to readme if you like 😃. 

There seems to be an issue with node-notifier https://github.com/mikaelbr/node-notifier/issues/361 
When running termin-buchen with `npm start` it would throw some Error -86 due to bad terminal-notifier binary. 
To fix it just copy the app from brew install into the node module of node-notifier vendor directory. 
Running in project root
```bash
brew install terminal-notifier
cp -i $(which terminal-notifier) ./node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
```
Will work as long as you won't do `npm i` 

error trace i got for info
```ts
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at spawn (node:child_process:761:9)
    at Object.execFile (node:child_process:351:17)
    at module.exports.fileCommandJson (/Users/tagyberg/vscode/termin-buchen-1/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/tagyberg/vscode/termin-buchen-1/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at NotificationCenter.sendNotification (/Users/tagyberg/vscode/termin-buchen-1/build/src/notifications/notification-center/index.js:8:36)
    at sendNotification (/Users/tagyberg/vscode/termin-buchen-1/build/src/notifications/send-notification.js:11:46)
    at startAutomation (/Users/tagyberg/vscode/termin-buchen-1/build/src/index.js:40:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by dmitry-kostin** [comment]
Have you tried `softwareupdate --install-rosetta` as suggested in the link you attached?
